/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ledyba_noiz2sa_Helper */

#ifndef _Included_org_ledyba_noiz2sa_Helper
#define _Included_org_ledyba_noiz2sa_Helper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ledyba_noiz2sa_Helper
 * Method:    onLoadJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ledyba_noiz2sa_Helper_onLoadJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
